
version: '3.9'
services:
  gateway:
   build:
     context: ./backend/gateway
     dockerfile: Dockerfile.dev
   container_name: api-gateway
   ports:
     - "8000:8000"
   environment:
     - NODE_ENV=development
     - ISSUE_SERVICE_URL={ISSUE_SERVICE_URL}
     - VERIFY_SERVICE_URL={VERIFY_SERVICE_URL}
   depends_on:
     - cred-issue-service
     - cred-verify-service

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - credIssue-service
      - credVerify-service

  credIssue-service:
    build:
      context: ./backend/Cred-issue/backend
      dockerfile: Dockerfile
    container_name: credIssue
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI={MONGODB_URI}
    depends_on:
      - mongodb

  credVerify-service:
    build:
      context: ./backend/Cred-verify/backend 
      dockerfile: Dockerfile
    container_name: credVerify  
    ports:
      - "5005:5005"
    environment:
      - MONGODB_URI={MONGODB_URI}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

volumes:
  mongodb_data: