
FROM node:20-alpine AS builder


FROM node:18-alpine AS production

WORKDIR /app

COPY package*.json ./
RUN npm install 
COPY --from=builder /app/gateway/dist ./dist

EXPOSE 3000

CMD ["npm", "run", "start"]