FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install


# Copy source code
COPY . .



# Expose port
EXPOSE 3005

# Start with nodemon for live reloading
CMD ["npm", "run", "dev"]