FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Install development tools
RUN npm install -g nodemon tsx typescript

# Copy source code
COPY . .

# Expose port
EXPOSE 3005

# Start with nodemon for live reloading
CMD ["npm", "run", "dev"]
# CMD ["nodemon", "--watch", ".", "--legacy-watch", "--ext", "ts,json", "--exec", "tsx", "server.ts"]
